# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    if: github.head_ref == 'develop' && (contains(github.event.pull_request.labels.*.name, 'release:patch') || contains(github.event.pull_request.labels.*.name, 'release:minor'))
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - run: |
          git config user.email "action@github.com"
          git config user.name "Github Action Bot"
      - uses: actions/setup-node@v1
        with:
          node-version: 12.0
      - run: npm i -g yarn
      - run: yarn --frozen-lockfile
      - id: version
        env:
          GITHUB_AUTH: ${{ github.token }}
          PATCH: ${{ contains(github.event.pull_request.labels.*.name, 'release:patch') }}
          MINOR: ${{ contains(github.event.pull_request.labels.*.name, 'release:minor') }}
        run: |
          ./src/scripts/version.sh
          git push --tags --no-verify origin ${{ github.head_ref }}
